"""
Markdown memo assembly.

Takes generated sections and assembles them into a final memo document.
"""

import logging
from datetime import datetime
from typing import Optional

from ..state import MemoState, MemoSections, ExtractedFacts

logger = logging.getLogger(__name__)


MEMO_TEMPLATE = """# {company} — Outside-In Research Memo

**Prepared by:** L'œil Automated Research  
**Date:** {date}  
**Signal Trigger:** {trigger}

---

## Executive Summary

{executive_summary}

---

## Company Overview

{company_overview}

{key_metrics_table}

---

## Market Context

{market_context}

---

## Signal Analysis

{signal_analysis}

---

## Risks & Considerations

{risks}

---

## Recommendation

{recommendation}

---

## Appendix: Data Sources

| Source | Status | Notes |
|--------|--------|-------|
{sources_table}

**Generated at:** {timestamp}  
**Confidence:** {confidence}

---

*This memo was generated by L'œil Research Memo Generator.*
"""


def format_key_metrics_table(facts: ExtractedFacts) -> str:
    """Generate a key metrics table from extracted facts."""
    rows = []
    
    # Website facts
    if facts.get("website"):
        w = facts["website"]
        if w.get("founded_year"):
            rows.append(f"| Founded | {w['founded_year']} | Website |")
        if w.get("headquarters"):
            rows.append(f"| HQ | {w['headquarters']} | Website |")
        if w.get("notable_customers"):
            customers = ", ".join(w["notable_customers"][:5])
            rows.append(f"| Customers | {customers} | Website |")
    
    # GitHub facts
    if facts.get("github"):
        g = facts["github"]
        if g.get("total_stars"):
            rows.append(f"| GitHub Stars | {g['total_stars']:,} | GitHub |")
        if g.get("public_repos_count"):
            rows.append(f"| Public Repos | {g['public_repos_count']} | GitHub |")
        if g.get("primary_languages"):
            langs = ", ".join(g["primary_languages"][:3])
            rows.append(f"| Tech Stack | {langs} | GitHub |")
    
    # Crunchbase facts
    if facts.get("crunchbase"):
        c = facts["crunchbase"]
        if c.get("total_raised"):
            rows.append(f"| Total Raised | ${c['total_raised']/1e6:.1f}M | Crunchbase |")
        if c.get("last_round_type"):
            rows.append(f"| Last Round | {c['last_round_type']} | Crunchbase |")
        if c.get("employee_range"):
            rows.append(f"| Employees | {c['employee_range']} | Crunchbase |")
    
    if rows:
        header = "### Key Metrics\n\n| Metric | Value | Source |\n|--------|-------|--------|\n"
        return header + "\n".join(rows)
    
    return ""


def format_sources_table(sources: list[str]) -> str:
    """Generate sources appendix table."""
    rows = []
    for source in sources:
        rows.append(f"| {source.title()} | ✅ Retrieved | — |")
    
    # Note missing sources
    all_sources = ["website", "github", "news", "crunchbase"]
    for source in all_sources:
        if source not in sources:
            rows.append(f"| {source.title()} | ⚠️ Not available | — |")
    
    return "\n".join(rows)


def assemble_memo(state: MemoState) -> str:
    """
    Assemble final memo from state.
    
    Args:
        state: Complete MemoState with all generated content
        
    Returns:
        Formatted markdown memo
    """
    sections = state.get("sections", {})
    facts = state.get("facts", {})
    
    # Get trigger info
    trigger = state.get("trigger", {})
    trigger_str = f"{trigger.get('signal', 'Manual review')}"
    if trigger.get("value"):
        trigger_str += f": {trigger['value']}"
    
    # Format components
    key_metrics = format_key_metrics_table(facts) if facts else ""
    sources_table = format_sources_table(state.get("sources_used", []))
    
    # Assemble memo
    memo = MEMO_TEMPLATE.format(
        company=state.get("company", "Unknown Company"),
        date=datetime.now().strftime("%B %Y"),
        trigger=trigger_str,
        executive_summary=sections.get("executive_summary", "[Not generated]"),
        company_overview=sections.get("company_overview", "[Not generated]"),
        key_metrics_table=key_metrics,
        market_context=sections.get("market_context", "[Not generated]"),
        signal_analysis=sections.get("signal_analysis", "[Not generated]"),
        risks=sections.get("risks", "[Not generated]"),
        recommendation=sections.get("recommendation", "[Not generated]"),
        sources_table=sources_table,
        timestamp=datetime.now().isoformat(),
        confidence=state.get("confidence", "medium"),
    )
    
    return memo


def save_memo(memo: str, filepath: str) -> str:
    """Save memo to file."""
    with open(filepath, "w") as f:
        f.write(memo)
    logger.info(f"Memo saved to {filepath}")
    return filepath
